			<p>
				<span tabindex=0 data-sentence=0 data-translation="Once upon a time there was a large group of frogs who always went to the forest to hang out and have fun.">Er was eens een grote groep kikkers die altijd naar het bos ging om rond te hangen en zich te vermaken.</span> <span tabindex=0 data-sentence=1 data-translation="They all sang and jumped until nightfall.">Ze zongen en sprongen allemaal tot de avond viel.</span> <span tabindex=0 data-sentence=2 data-translation="They always laughed really hard and were inseparable.">Ze lachten altijd heel hard en waren onafscheidelijk.</span>
			</p>
			<p>
				<span tabindex=0 data-sentence=3 data-translation="One day, during their usual outing, they decided to go to a new forest.">Op een dag, tijdens hun gebruikelijke uitje, besloten ze naar een nieuw bos te gaan.</span> <span tabindex=0 data-sentence=4 data-translation="In the middle of their usual games, three of the frogs fell into a deep pit that none of them had noticed before.">In het midden van hun gebruikelijke spelletjes vielen drie van de kikkers in een diepe put die niemand van hen eerder had opgemerkt.</span> <span tabindex=0 data-sentence=5 data-translation="The rest were shocked.">De rest was geschokt.</span> <span tabindex=0 data-sentence=6 data-translation="They looked at the bottom of the well and saw that it was too deep.">Ze keken naar de bodem van de put en zagen dat die te diep was.</span> <span tabindex=0 data-sentence=7 data-translation="“We lost them,” they said.">“We zijn ze kwijt,” zeiden ze.</span>
			</p>
			<p>
				<span tabindex=0 data-sentence=8 data-translation="The three fallen frogs tried to climb the walls of the pit, but it was very difficult.">De drie gevallen kikkers probeerden de wanden van de put te beklimmen, maar het was erg moeilijk.</span> <span tabindex=0 data-sentence=9 data-translation="They barely rose an inch and then fell back down.">Ze kwamen amper een centimeter omhoog en vielen dan weer naar beneden.</span>
			</p>
			<p>
				<span tabindex=0 data-sentence=10 data-translation="The others began to notice that their efforts were futile.">De anderen begonnen op te merken dat hun inspanningen nutteloos waren.</span> <span tabindex=0 data-sentence=11 data-translation="How would they ever manage to climb such a high wall?">Hoe zouden ze er ooit in slagen om zo’n hoge wand te beklimmen?</span> <span tabindex=0 data-sentence=12 data-translation="They thought they should just give up.">Ze dachten dat ze het gewoon moesten opgeven.</span> <span tabindex=0 data-sentence=13 data-translation="There was nothing that could be done.">Er was niets aan te doen.</span>
			</p>
			<p>
				<span tabindex=0 data-sentence=14 data-translation="Two of the frogs heard those comments and gave up.">Twee van de kikkers hoorden die opmerkingen en gaven het op.</span> <span tabindex=0 data-sentence=15 data-translation="They thought the others were right.">Ze dachten dat de anderen gelijk hadden.</span> <span tabindex=0 data-sentence=16 data-translation="The third frog, on the other hand, continued to climb and fall, but after a few hours it managed to surface.">De derde kikker daarentegen bleef klimmen en vallen, maar na een paar uur slaagde hij erin om naar de oppervlakte te komen.</span>
			</p>
			<p>
				<span tabindex=0 data-sentence=17 data-translation="The others were amazed.">De anderen waren verbaasd.</span> <span tabindex=0 data-sentence=18 data-translation="One of them asked, “How did you do it?”">Een van hen vroeg: “Hoe heb je het gedaan?”</span> <span tabindex=0 data-sentence=19 data-translation="The frog, however, did not answer.">De kikker gaf echter geen antwoord.</span> <span tabindex=0 data-sentence=20 data-translation="He was deaf.">Hij was doof.</span>
			</p>
